---
title: "Mapping food system institutions and policies in Niger"
author: "HEMA Aboubacar"
date: '`r format (Sys.Date(), "%d %B %Y")`'
output: 
  officedown::rdocx_document:
    mapstyles:
      Normal: ['First Paragraph']
---

```{r setup, include = FALSE, warning=FALSE, echo = FALSE}
knitr::opts_chunk$set(
	echo = FALSE,
	message = FALSE,
	warning = FALSE
)
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
library(officedown)
library(officer)

fp <- fp_par(
  text.align = "center", 
  padding.bottom = 20, padding.top = 120, 
  border.bottom = fp_border())

ft <- fp_text(shading.color='#EFEFEF', bold = F)
```


<!---BLOCK_TOC--->

\newpage

```{r}
library(dplyr)
library(expss)
library(openxlsx)
library(readxl)
library(tidyverse)
library(janitor)
library(gtsummary)
library(data.table)
library(stringr)
library(compareDF)
library(sjlabelled)
library(lmtest)
library(sandwich)
```


```{r}
rm(list = ls())
```

```{r}
library(haven)
EVALUATION_DES_CAPACITES_Hema <- read_dta(paste0(here::here(),"/data/IFPRI NIGER - EVALUATION DES CAPACITES_Hema.dta"))

```


```{r}
EVALUATION_DES_CAPACITES_Hema$organis
EVALUATION_DES_CAPACITES_Hema$q_iii_10_2
```


```{r}
library(tidyr)

stocks <- tibble(
  time = as.Date("2009-01-01") + 0:9,
  X = rnorm(10, 0, 1),
  Y = rnorm(10, 0, 2),
  Z = rnorm(10, 0, 4)
)
stocksm <- stocks %>% gather(stock, price, -time)
stocksm %>% spread(stock, price)
stocksm %>% spread(time, price)
```

```{r}
EVALUATION_DES_CAPACITES_Hema$institutions<-1

EVALUATION_DES_CAPACITES_Hema$organis2<-paste0("I",1:343)


# df=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis, q_iii_10_2,q_iii_1) %>% 
#   spread(organis, q_iii_10_2)
```

```{r}
library(tidyr)


df_1=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_1,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_1) %>% slice(-1)
df_2=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_2,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_2) %>% slice(-1)
df_3=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_3,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_3) %>% slice(-1)
df_4=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_4,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_4) %>% slice(-1)
df_5=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_5,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_5) %>% slice(-1)
df_6=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_6,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_6) %>% slice(-1)
df_7=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_7,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_7) %>% slice(-1)
df_8=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_8,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_8) %>% slice(-1)
df_9=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_9,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_9) %>% slice(-1)
df_10=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_10,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_10) %>% slice(-1)
df_11=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_11,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_11) %>% slice(-1)
df_12=EVALUATION_DES_CAPACITES_Hema %>% dplyr::select(organis2, q_iii_2_12,institutions) %>%
  pivot_wider(names_from = organis2, values_from = institutions) %>% 
 dplyr::rename(actor = q_iii_2_12) %>% slice(-1)
# q_iii_2_2
# q_iii_2_3
# q_iii_2_4
# q_iii_2_5
# q_iii_2_6
# q_iii_2_7
# q_iii_2_8
# q_iii_2_9
# q_iii_2_10
# q_iii_2_11
# q_iii_2_12
```


```{r}
df_matrix = plyr::rbind.fill(df_1,
                             df_2,
                             df_3,
                             df_4,
                             df_5,
                             df_6,
                             df_7,
                             df_8,
                             df_9,
                             df_10,
                             df_11,
                             df_12)
```

```{r}
df_matrix = df_matrix %>%
  group_by(actor) %>%
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE)))
```

```{r}
df_matrix = df_matrix %>% mutate(r_assigns=sample(c("Etat","Non Etat"), nrow(df_matrix), replace=TRUE))
```

```{r}
df_matrix = df_matrix %>%
  group_by(r_assigns) %>%
  summarise(across(where(is.numeric), ~ sum(.x, na.rm = TRUE)))
```


```{r}
write_csv(df_matrix,"matrix.csv")
```


```{r}
df_matrix[is.na(df_matrix)] <- 0
```

```{r}
write_csv(df_matrix,"matrix.csv")
```

